homepage/urls.py
from django.urls import path, include
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('add_status', views.add_status_view, name="add_status"),
    path('del_status/<int:id>', views.del_status_view, name='del_status'),
]

lab7/urls.py
from django.urls import path, include
from . import views

app_name = 'lab7'

urlpatterns = [
    path('', views.lab7_view, name='view_lab7'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('lab7/', include('lab7.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
	title = models.CharField(max_length=30)
	description = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

lab7/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Please do not leave this empty!',
    }
    title_attrs = {
        'type': 'text',
        'class': 'status-form-input',
        'placeholder':'Enter new status...'
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 8,
        'class': 'status-form-textarea',
        'placeholder':'Enter status description...'
    }

    title = forms.CharField(label='', required=True, max_length=30, widget=forms.TextInput(attrs=title_attrs))
    description = forms.CharField(label='', required=True, max_length=300, widget=forms.Textarea(attrs=description_attrs))

homepage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Status
from .forms import Status_Form

# Create your views here.
response = {}

def index_view(request):
	status = Status.objects.all().order_by('-created_date')
	response['status'] = status
	response['status_form'] = Status_Form
	return render(request, 'index.html', response)

def add_status_view(request):
	form = Status_Form(request.POST or None)

	if( (request.method == 'POST') and form.is_valid() ):
		response['title'] = request.POST['title']
		response['description'] = request.POST['description']
		status = Status(title=response['title'], description=response['description'])
		status.save()
		return HttpResponseRedirect('/')
	else:
		return HttpResponseRedirect('/')

def del_status_view(request, id):
	Status.objects.get(pk=id).delete()
	return HttpResponseRedirect('/')

lab7/views.py
from django.shortcuts import render

# Create your views here.

def lab7_view(request):
    return render(request, 'lab7.html')

homepage/templates/index.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load static %}
<html lang="en">
    
  <head>
        
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- App CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/home_style.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
    crossorigin="anonymous">

    <!-- Website Title  -->
    <title>PPW Story 6 | Primo G U</title>

  </head>

  <body>

    <h1 class="main-title"><strong>HALO! APA KABAR?</strong></h1>

    <section name="input-list" id="input-list">
        <div class="container">
            <form id="form" method="POST" action="{% url 'homepage:add_status' %}">
                <h2><strong>Input Status</strong></h2>
                {% csrf_token %}
                {{ status_form|crispy }}
                <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            </form>
        </div>
    </section>

    <section name="my-list" id="my-list">
        <div class="container">
            <h2 class="my-list-title">My Status</h2>

                {% if status %}
                    {% for data in status %}
                    <div class="card bg-dark text-white">

                        <div class="card-header">
                            <div class="status-list-title">
                                {{data.title}}
                            </div>
                        </div>

                        <div class="card-body">
                            <div class="status-list-date-added">
                                {{data.created_date}}
                            </div>
                            <hr>
                            <div class="status-list-description">
                                {{data.description}}
                            </div>
                        </div>

                        <div class="card-footer">
                            <a href="{% url 'homepage:del_status' data.id %}"
                            class="btn btn-danger btn-block" 
                            data-id="{{data.id}}"
                            role="button"><strong>Delete Status</strong></a>
                        </div>

                    </div>
                    <br>
                    {% endfor %}

                {% else %}          
                <div class="alert alert-danger text-center">
                    <strong>Oops!</strong> Tidak ada data status.
                </div>
                {% endif %}

            </div>
        </div>
    </section>

    <!-- Optional JavaScript -->
    <!-- jQuery library -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
    crossorigin="anonymous"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
    crossorigin="anonymous"></script>

    <!-- Bootstrap JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
    crossorigin="anonymous"></script>

  </body>

</html>

lab7/templates/lab7.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

    <head>

        <!-- Required meta tags -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        
        <!-- App CSS -->
        <link rel="stylesheet" href="{% static 'css/lab7_style.css' %}" />
    
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" 
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
        crossorigin="anonymous">

        <!-- Install jQuery Library -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

        <!-- App JavaScript -->
        <script src="{% static 'js/lab7_script.js' %}"></script>

        <!-- Website Page Title -->
        <title>PPW Story 7 | Primo Giancarlo Uneputty</title>

    </head>

    <body style="background-color: rgb(255, 255, 255);">
        
        <div class="custom-control custom-switch" id="change">
            <input type="checkbox" class="custom-control-input" id="customSwitch1" onchange="change()">
            <label class="custom-control-label" for="customSwitch1" id="toggle">Change Theme</label>
        </div>
    
        <div>
            <h1>Hi! I'm Primo Giancarlo!</h1>
        </div>
    
        <div class="accordion">
            <button class="accord" onclick="accordion()"><strong>Activity</strong></button>
            <div class="panel">
                <p><strong>Eat</strong></p>
                <p><strong>Sleep</strong></p>
                <p><strong>Die</strong></p>
            </div>

            <button class="accord" onclick="accordion()"><strong>Experience</strong></button>
            <div class="panel">
                <p><strong>Perlap RKF 2019</strong></p>
            </div>

            <button class="accord" onclick="accordion()"><strong>Achievements</strong></button>
            <div class="panel">
                <p><i>This section is empty</i></p>
            </div>
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery library -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
        crossorigin="anonymous"></script>

        <!-- Popper JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
        crossorigin="anonymous"></script>

        <!-- Bootstrap JavaScript -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
        crossorigin="anonymous"></script>

    </body>

</html>